name: fire_crud_flutter
description: "Purpose built collection widgets for easily displaying your data via fire_crud"
version: 1.3.1+1
repository: https://github.com/ArcaneArts/fire_crud_flutter
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  fire_api: ">=1.3.0 <2.0.0"
  fire_crud: ">=3.1.1 <4.0.0"
  toxic_flutter: '>=1.0.1 <2.0.0'
  toxic: '>=1.3.0 <2.0.0'
  pylon: '>=3.0.4 <4.0.0'
  throttled: ">=1.0.1 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: